<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionsTableSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'name_en' => 'Yerevan',
                'name_hy' => 'Երևան',
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Abovyan',
                'name_hy' => 'Աբովյան',
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Agarak',
                'name_hy' => 'Ագարակ',
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Alaverdi',
                'name_hy' => 'Ալավերդի',
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Aparan',
                'name_hy' => 'Ապարան',
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Ararat',
                'name_hy' => 'Արարատ',
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Artik',
                'name_hy' => 'Արթիկ',
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Armavir',
                'name_hy' => 'Արմավիր',
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Artashat',
                'name_hy' => 'Արտաշատ',
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Byureghavan',
                'name_hy' => 'Բյուրեղավան',
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Gavar',
                'name_hy' => 'Գավառ',
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Gyumri',
                'name_hy' => 'Գյումրի',
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Goris',
                'name_hy' => 'Գորիս',
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Dilijan',
                'name_hy' => 'Դիլիջան',
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Eghegnadzor',
                'name_hy' => 'Էղեգնաձոր',
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Eghvard',
                'name_hy' => 'Եղվարդ',
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Zovuni',
                'name_hy' => 'Զովունի',
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Ejmiatsin',
                'name_hy' => 'Էջմիացին',
                'order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Tairov',
                'name_hy' => 'Թաիրով',
                'order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Talin',
                'name_hy' => 'Թալին',
                'order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Tumanyan',
                'name_hy' => 'Թումանյան',
                'order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Tsaghkadzor',
                'name_hy' => 'Ծաղկաձոր',
                'order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Ijevan',
                'name_hy' => 'Իջևան',
                'order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Kapan',
                'name_hy' => 'Կապան',
                'order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Hrazdan',
                'name_hy' => 'Հրազդան',
                'order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Masis',
                'name_hy' => 'Մասիս',
                'order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Maralik',
                'name_hy' => 'Մարալիկ',
                'order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Martuni',
                'name_hy' => 'Մարտունի',
                'order' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Metsamor',
                'name_hy' => 'Մեծամոր',
                'order' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Meghri',
                'name_hy' => 'Մեղրի',
                'order' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Noyemberyan',
                'name_hy' => 'Նոյեմբերյան',
                'order' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Nor Hachn',
                'name_hy' => 'Նոր Հաճն',
                'order' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Charentsavan',
                'name_hy' => 'Չարենցավան',
                'order' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Jrvezh',
                'name_hy' => 'Ջրվեժ',
                'order' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Sisian',
                'name_hy' => 'Սիսիան',
                'order' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Spitak',
                'name_hy' => 'Սպիտակ',
                'order' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Stepanakert',
                'name_hy' => 'Ստեփանակերտ',
                'order' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Stepanavan',
                'name_hy' => 'Ստեփանավան',
                'order' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Sevan',
                'name_hy' => 'Սևան',
                'order' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Vayq',
                'name_hy' => 'Վայք',
                'order' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Vanadzor',
                'name_hy' => 'Վանաձոր',
                'order' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Vardenis',
                'name_hy' => 'Վարդենիս',
                'order' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Vedi',
                'name_hy' => 'Վեդի',
                'order' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Tashir',
                'name_hy' => 'Տաշիր',
                'order' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Paraqar',
                'name_hy' => 'Փարաքար',
                'order' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Qanaqeravan',
                'name_hy' => 'Քանաքեռավան',
                'order' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Qajaran',
                'name_hy' => 'Քարաջան',
                'order' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Qasakh',
                'name_hy' => 'Քասախ',
                'order' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        Region::insert($data);
    }
}
